my_app_rubrique:
    resource: "@MyAppRubriqueBundle/Resources/config/routing.yml"
    prefix:   /

my_app_esprit:
    resource: "@MyAppEspritBundle/Resources/config/routing.yml"
    prefix:   /
# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Acme/UserBundle/Resources/config/routing.yml

user_one_registration:
    pattern:  /register/user-one
    defaults: { _controller: MyAppUserBundle:RegistrationUserOne:register }

user_two_registration:
    pattern:  /register/user-two
    defaults: { _controller: MyAppUserBundle:RegistrationUserTwo:register }    


