parameters:
#    my_app_rubrique.example.class: MyApp\RubriqueBundle\Example

services:
#    my_app_rubrique.example:
#        class: %my_app_rubrique.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
